---
android: RESET_BETWEEN_SCENARIOS=1 PLATFORM=android -r features/support -r features/android/support -r features/android/helpers -r features/step_definitions -r features/android/pages/  --format html --out results/reports.html --format pretty   --format junit --out results/junit --tags ~@ios --tags ~@wip

ios: SCREENSHOT_PATH=results/ APP_BUNDLE_PATH=Desk-cal.app RESET_BETWEEN_SCENARIOS=1 PLATFORM=ios -r features/support -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages  --format html --out results/reports.html --format pretty   --format junit --out results/junit --tags ~@android --tags ~@wip

